name: A workflow for covid-19
on: push

jobs:
  build:
    name: Get covid info
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        npm install
        npm run all
  run:
    runs-on: ubuntu-latest
    steps:
    - name: get_data
    - uses: actions/checkout@v1
    - uses: ./
      with: 
        country: 'Brazil'
    - name: telegram
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        args: Country ${{ steps.get_data.outputs.country }}